WITH CARTEIRINHA_CHAVE AS (
SELECT DISTINCT
A.COD_CARTEIRINHA_ORIGINAL,
A.COD_BENEFICIARIO_CHAVE
FROM `self-service-saude.VW_CONS_SAU.DM_MGR_VIDA` A
INNER JOIN `self-service-saude.VW_CONS_SAU.TB_EXP_ONCO` B
ON A.COD_CARTEIRINHA_ORIGINAL = B.COD_CARTEIRINHA_ORIGINAL

)


,DATA AS (SELECT 
DATE_TRUNC(DATE_SUB(MIN(DATA_OBITO), INTERVAL 6 MONTH), MONTH)  DAT_INICIAL,
DATE_TRUNC(MAX(DATA_OBITO), MONTH) DAT_FINAL


FROM `self-service-saude.VW_CONS_SAU.TB_EXP_ONCO` )

, PERIODO AS (
SELECT DISTINCT 
DAT_INICIAL 
FROM DATA
CROSS JOIN UNNEST(GENERATE_DATE_ARRAY(DATA.DAT_INICIAL, DATA.DAT_FINAL, INTERVAL 1 MONTH)) AS DAT_INICIAL)

,DATA_CROSS  AS (
SELECT 
COD_CARTEIRINHA_ORIGINAL,
DAT_INICIAL AS DATA_OBITO2
FROM `self-service-saude.VW_CONS_SAU.TB_EXP_ONCO`
CROSS JOIN PERIODO)


,BENEF_OBITO AS (
SELECT 
A.COD_CARTEIRINHA_ORIGINAL,
C.COD_BENEFICIARIO_CHAVE,
A.DATA_OBITO2 DATA_REF,
B.DATA_OBITO

FROM DATA_CROSS A
LEFT JOIN `self-service-saude.VW_CONS_SAU.TB_EXP_ONCO` B
ON  A.COD_CARTEIRINHA_ORIGINAL = B.COD_CARTEIRINHA_ORIGINAL 
AND A.DATA_OBITO2 = DATE_TRUNC(B.DATA_OBITO, MONTH)
LEFT JOIN CARTEIRINHA_CHAVE C
ON A.COD_CARTEIRINHA_ORIGINAL = C.COD_CARTEIRINHA_ORIGINAL)


, SINISTRO_OBITO AS(
SELECT 
A.COD_CARTEIRINHA_ORIGINAL,
A.DATA_REF,
A.DATA_OBITO,
IFNULL(ROUND(SUM(B.VAL_SINISTRO),2),0) AS VAL_SINISTRO
FROM BENEF_OBITO A
LEFT JOIN `self-service-saude.VW_CONS_SAU.DM_MGR_SINISTRO` B
ON  A.COD_BENEFICIARIO_CHAVE = B.COD_BENEFICIARIO_CHAVE
AND A.DATA_REF = DATE_TRUNC(B.DAT_ATENDIMENTO, MONTH)
GROUP BY 1,2,3)


SELECT 
	COD_CARTEIRINHA_ORIGINAL,
	DATA_REF,
	DATA_OBITO,
	ROUND(VAL_SINISTRO,2) VAL_SINISTRO,
	ROUND(VAL_SINISTRO_6_MESES_ANTES,2) VAL_SINISTRO_6_MESES_ANTES,
	ROUND(VAL_SINISTRO_3_MESES_ANTES,2) VAL_SINISTRO_3_MESES_ANTES
FROM (
	SELECT
		COD_CARTEIRINHA_ORIGINAL,
		DATA_REF,
		DATA_OBITO,
		VAL_SINISTRO,
		IFNULL(SUM(IFNULL(VAL_SINISTRO,0)) OVER (PARTITION BY COD_CARTEIRINHA_ORIGINAL
			ORDER BY DATA_REF ASC
			ROWS BETWEEN 5 PRECEDING AND CURRENT ROW
			),0) VAL_SINISTRO_6_MESES_ANTES,
		IFNULL(SUM(IFNULL(VAL_SINISTRO,0)) OVER (PARTITION BY COD_CARTEIRINHA_ORIGINAL
			ORDER BY DATA_REF ASC
			ROWS BETWEEN2 PRECEDING AND CURRENT ROW)
		,0) VAL_SINISTRO_3_MESES_ANTES
		FROM SINISTRO_OBITO)