EXP_TOP_ABERTO BACKUP
CREATE OR REPLACE TABLE `self-service-saude.VW_CONS_SAU.TB_EXP_CLASSES_SINISTRO_TOP_ABERTO` AS

WITH CTE_SIN_1 AS(
SELECT T1.COD_BENEFICIARIO_CHAVE 
      ,T1.NME_FANTASIA_PRESTADOR 
      ,T1.VAL_SINISTRO
      ,T1.FLG_TIPO_SINISTRO
      ,T1.COD_PRESTADOR
      ,T1.FLG_LIMINAR 
      ,T1.DAT_EXECUCAO
      ,T2.DSC_SERVICO_COMPL AS DSC_SERVICO 
      ,T2.DSC_GRUPO_SERVICO
      ,T2.DSC_SUB_GRUPO_SERV AS DSC_SUBGRUPO 
      ,T1.QTD_SERVICO
      ,T3.NME_GRP_ECON_PREST 
      ,T3.NME_MUNICIPIO 
      ,T3.SIG_UF 
      ,T4.DSC_ESPECIALIDADE 
      ,CONCAT(CAST(EXTRACT(YEAR FROM T1.DAT_EXECUCAO) AS STRING),CAST(EXTRACT(MONTH FROM T1.DAT_EXECUCAO) AS STRING)) AS ANO_MES
  FROM `self-service-saude.VW_CONS_SAU.DM_MGR_SINISTRO` T1
  LEFT JOIN  `self-service-saude.VW_CONS_SAU.TB_DIM_SERVICO` T2
    ON T1.COD_SERVICO = T2.COD_SERVICO 
  LEFT JOIN  `self-service-saude.VW_CONS_SAU.TB_DIM_PRESTADOR` T3
    ON T1.COD_PRESTADOR = T3.COD_PRESTADOR 
  LEFT JOIN `self-service-saude.SANDBOX_DITER.TB_DIM_CLASSE_MEDICA_DITER` T4
    ON T1.COD_SERVICO = T4.COD_SERVICO 
 WHERE T1.DAT_EXECUCAO >= '2017-01-01'
   AND T1.DAT_EXECUCAO <= DATE_TRUNC(DATE_SUB(CURRENT_DATE,INTERVAL 1 MONTH),MONTH))

,CTE_SIN_2 AS (
SELECT T1.COD_BENEFICIARIO_CHAVE
      ,T1.NME_FANTASIA_PRESTADOR
      ,T1.VAL_SINISTRO
      ,T1.FLG_TIPO_SINISTRO
      ,T1.COD_PRESTADOR
      ,T1.DSC_ESPECIALIDADE
      ,T1.DSC_SERVICO 
      ,T1.DSC_GRUPO_SERVICO
      ,T1.DSC_SUBGRUPO
      ,T1.QTD_SERVICO
      ,T1.NME_GRP_ECON_PREST 
      ,T1.NME_MUNICIPIO 
      ,T1.SIG_UF
      ,CASE WHEN UPPER(TRIM(T1.DSC_GRUPO_SERVICO)) = 'JUDICIAL'
             AND T1.FLG_LIMINAR = 'S'
            THEN 1
            ELSE 0
        END AS FLG_LIMINAR
      ,CAST(CASE WHEN ANO_MES IN ('20171','20172','20173')
            THEN '1'
            WHEN ANO_MES IN ('20174','20175','20176')
            THEN '2'
            WHEN ANO_MES IN ('20177','20178','20179')
            THEN '3'
            WHEN ANO_MES IN ('201710','201711','201712')
            THEN '4'
            WHEN ANO_MES IN ('20181','20182','20183')
            THEN '5'
            WHEN ANO_MES IN ('20184','20185','20186')
            THEN '6'
            WHEN ANO_MES IN ('20187','20188','20189')
            THEN '7'
            WHEN ANO_MES IN ('201810','201811','201812')
            THEN '8'
            WHEN ANO_MES IN ('20191','20192','20193')
            THEN '9'
            WHEN ANO_MES IN ('20194','20195','20196')
            THEN '10'
            WHEN ANO_MES IN ('20197','20198','20199')
            THEN '11'
            WHEN ANO_MES IN ('201910','201911','201912')
            THEN '12'
            ELSE '0' 
         END AS NUMERIC)AS COD_TRIMESTRE
  FROM CTE_SIN_1 T1      
)

SELECT T1.*
      ,T2.NME_FANTASIA_PRESTADOR
      ,T2.FLG_TIPO_SINISTRO
      ,T2.COD_PRESTADOR
      ,T2.DSC_ESPECIALIDADE
      ,T2.DSC_SERVICO 
      ,T2.DSC_GRUPO_SERVICO
      ,T2.DSC_SUBGRUPO
      ,T2.NME_GRP_ECON_PREST 
      ,T2.NME_MUNICIPIO 
      ,T2.SIG_UF      
      ,T2.FLG_LIMINAR
      ,ROUND(SUM(VAL_SINISTRO),2) AS VAL_SINISTRO
      ,SUM(T2.QTD_SERVICO) AS QTD_SERVICO
  FROM `self-service-saude.VW_CONS_SAU.TB_EXP_CLASSES_SINISTRO_TOP` T1
  LEFT JOIN CTE_SIN_2 T2
    ON T1.COD_BENEFICIARIO_CHAVE = T2.COD_BENEFICIARIO_CHAVE
   AND T1.TRI                    = T2.COD_TRIMESTRE
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34