SELECT  DISTINCT E.COD_PREF_EMPRESA, E.COD_EMPRESA, E.FLG_COPART_REVERS,
case WHEN PS.COD_TIPO_PRODUTO = 'A' THEN 'ADMINISTRADO'
				WHEN PS.COD_TIPO_PRODUTO = 'P' THEN 'PME'
				WHEN PS.COD_TIPO_PRODUTO = 'G' AND (E.FLG_CONTR_ADESAO = 'N' OR E.FLG_CONTR_ADESAO IS NULL) THEN 'EMPRESARIAL'
				WHEN PS.COD_TIPO_PRODUTO = 'G' AND E.FLG_CONTR_ADESAO = 'S' THEN 'ADESAO'
				WHEN PS.COD_TIPO_PRODUTO = 'I' THEN 'INDIVIDUAL'
				ELSE 'NÃO IDENTIFICADO' END AS CARTEIRA,

--CASE WHEN E.DAT_AVISO_PEND <> TO_DATE('99991231000000','YYYYMMDDHH24MISS') THEN 'S' ELSE 'N' END as C_1,
--E.DAT_AVISO_PEND,
CASE WHEN FC.COD_SIT_PAGAMENTO = 90 THEN 'PAGO' 
	 WHEN FC.COD_SIT_PAGAMENTO = 30 THEN 'CANCELADO' 
	 WHEN FC.COD_SIT_PAGAMENTO = 50 THEN 'PENDENTE' 
END as SIT_PAGAMENTO
, E.DAT_FIM_PAM
, E.DAT_FIM_PAO,
--CASE WHEN ( E.DAT_FIM_PAM <> TO_DATE('99991231000000','YYYYMMDDHH24MISS') 	AND E.DAT_FIM_PAO <> TO_DATE('99991231000000','YYYYMMDDHH24MISS') ) THEN 'INATIVA' 
--		ELSE 'ATIVA' END as STATUS,
E.COD_CIA as COD_CIA_SEGURADORA,
E.COD_ESTR_VENDA as COD_ESTR_VENDA,
E.COD_PROD as COD_PRODUTO,
E.COD_SUCURSAL as COD_SUCURSAL,
E.DAT_AVISO_PEND as DAT_AVISO_PEND,
E.DAT_INICIO_PAM as DAT_INICIO_PAM,
E.DSC_RAZAO_SOCIAL as DSC_RAZAO_SOCIAL,
--E.NUM_APOLICE as NUM_APOLICE,
FORMAT("%.0F", FC.NUM_REF) as NUM_REF,
FORMAT_TIMESTAMP("%Y-%m-%d",FC.DAT_VENCIMENTO) as DAT_VENCIMENTO,
FC.VAL_RECUPERAR as VAL_RECUPERAR,
FC.COD_LANC_FINANC as COD_LANC_FINANC,
FORMAT_TIMESTAMP("%Y-%m-%d",FC.DAT_REFERENCIA) as DAT_REFERENCIA
FROM (SELECT 
		   COD_EMPRESA
		 , COD_PREF_EMPRESA
		 , DSC_RAZAO_SOCIAL
		 , FLG_CONTR_ADESAO
		 , COD_CIA
		 , COD_ESTR_VENDA
		 , COD_PROD
		 , COD_SUCURSAL
		 , DAT_AVISO_PEND
		 , DAT_INICIO_PAM
     , DAT_FIM_PAM
     , DAT_FIM_PAO
     , FLG_COPART_REVERS
		 , DENSE_RANK() OVER (PARTITION BY COD_PREF_EMPRESA, COD_EMPRESA ORDER BY TMP_COMMIT_ORIGEM_CDC DESC) RANK_EMP
	FROM OW_LAND_SAU_PRD.EMPRESAS) E
  INNER JOIN 
     (SELECT 
		   COD_EMPRESA
		 , COD_PREF_EMPRESA
		 , COD_LOCAL
		 , DENSE_RANK() OVER (PARTITION BY COD_PREF_EMPRESA, COD_EMPRESA, COD_LOCAL ORDER BY TMP_COMMIT_ORIGEM_CDC DESC) RANK_LE
FROM OW_LAND_SAU_PRD.LOCAL_EMPRESA)	EL	 
   ON E.COD_PREF_EMPRESA = EL.COD_PREF_EMPRESA 
   AND E.COD_EMPRESA = EL.COD_EMPRESA
   AND RANK_LE = 1
  INNER JOIN   
     (SELECT 
		   COD_EMPRESA
		 , COD_PREF_EMPRESA
		 , COD_SIT_PAGAMENTO
		 , IDC_TIPO_FATURA		 
		 , NUM_REF 
		 , DAT_VENCIMENTO
		 , VAL_RECUPERAR
		 , COD_LANC_FINANC 
		 , DAT_REFERENCIA		 
		 , DENSE_RANK() OVER (PARTITION BY COD_PREF_EMPRESA, COD_EMPRESA, CAST(NUM_REF AS STRING) ORDER BY TMP_COMMIT_ORIGEM_GG DESC) RANK_FC
		FROM OW_LAND_SAU_PRD.SINISTRO_RECUP_FC)	FC 
	ON EL.COD_PREF_EMPRESA = FC.COD_PREF_EMPRESA 
	AND EL.COD_EMPRESA = FC.COD_EMPRESA
	AND FC.RANK_FC = 1
INNER JOIN (SELECT 
            C.COD_PROD, C.COD_TIPO_PRODUTO
            ,DENSE_RANK() OVER (PARTITION BY C.COD_PROD ORDER BY TMP_COMMIT_ORIGEM_CDC DESC) AS RANKING_C
            FROM `OW_LAND_SAU_PRD.PRODUTO_SAUDE` AS C) AS PS         
ON E.COD_PROD = PS.COD_PROD
AND PS.RANKING_C=1  
  
WHERE E.RANK_EMP = 1  
  AND (FC.IDC_TIPO_FATURA = 'P')
 -- AND E.FLG_COPART_REVERS = 'N'
 AND (FC.COD_SIT_PAGAMENTO <> 90)  