-- CREATE OR REPLACE TABLE `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_EXP_SDCC405_VPP` AS

WITH PROGRAMA_SAUDE AS (

SELECT * FROM (SELECT 
COD_BENEFICIARIO_CHAVE,
DAT_INICIO_PROGRAMA_SAUDE_ATIVA_1,
DSC_PROGRAMA_SAUDE_ATIVA_1,
ROW_NUMBER() OVER(PARTITION BY COD_BENEFICIARIO_CHAVE) R_RNK
FROM (SELECT  
CONCAT(COD_PREF_EMPRESA, COD_EMPRESA, COD_FAMILIAR_BENEF, COD_RDP)COD_BENEFICIARIO_CHAVE, 
DAT_INICIO_PROGRAMA_SAUDE_ATIVA_1,
DSC_PROGRAMA_SAUDE_ATIVA_1
FROM `self-service-saude.SBX_ESTRATIFICACAO.TB_BENEFICIARIO_SINISTRO`))WHERE R_RNK = 1)

,CRM_MEDICO_CC AS (select * from (
SELECT   
 
num_conselho,
row_number() over(partition by num_conselho) d_rnk

FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_MEDICOS_CC` ) where d_rnk = 1)


,SOLIC_TRATATIVA AS (
SELECT * FROM (
SELECT 
Id,
LastModifiedDate,
COD_GUIA_SOLIC_PRINC__c,
COD_SEGURADO__c, 
COD_SOLIC_TRATATIVA__c,
FRM_NUM_SENHA_AUTORIZ__c,
upper(IDC_FINALIZACAO__c) DSC_TIPO_FINALIZACAO,
upper(IDC_STATUS_TRATATIVA__c) DSC_STATUS_TRATIVA,
ROW_NUMBER() OVER(PARTITION BY Id order by LastModifiedDate desc) R_RNK

FROM `self-service-corp.OW_SFDC_MAIN_PRD.SOLIC_TRATATIVA__c` ) WHERE R_RNK = 1)


, SEGURADO AS (
SELECT * FROM (
SELECT 
  Id
, LastModifiedDate
, COD_BENEFICIARIO__c
, ROW_NUMBER() OVER(PARTITION BY ID ORDER BY LastModifiedDate DESC) R_RNK



FROM `self-service-corp.OW_SFDC_MAIN_PRD.SEGURADO__c` )WHERE R_RNK = 1)


,GI AS(
	SELECT * FROM (
SELECT
 SOLIC.Id,
 SOLIC.LastModifiedDate,
 SEGU.COD_BENEFICIARIO__c,
 SOLIC.COD_GUIA_SOLIC_PRINC__c,
 SOLIC.COD_SEGURADO__c,
 SOLIC.COD_SOLIC_TRATATIVA__c,
 SOLIC.FRM_NUM_SENHA_AUTORIZ__c,
 SOLIC.DSC_STATUS_TRATIVA,
 SOLIC.DSC_TIPO_FINALIZACAO,
 ROW_NUMBER() OVER(PARTITION BY SOLIC.ID ORDER BY SOLIC.LastModifiedDate DESC) R_RNK

 FROM SOLIC_TRATATIVA SOLIC
 LEFT JOIN SEGURADO SEGU
 ON SOLIC.COD_SEGURADO__c = SEGU.Id
 )WHERE R_RNK = 1
) 


, SOLIC_TRATATIVA_AD AS (
SELECT * FROM (SELECT 
Id, 
LastModifiedDate, 
COD_SEGURADO__c, 
COD_TRATATIVA_AD__c, 
FRM_NUM_SENHA_AUTORIZ__c,
ROW_NUMBER() OVER(PARTITION BY ID ORDER BY LastModifiedDate  DESC) R_RNK

FROM `self-service-corp.OW_SFDC_MAIN_PRD.SOLIC_TRATATIVA__c` ) WHERE R_RNK = 1)

, TRATATIVA AS (

select * from ( SELECT  
Id, 
LastModifiedDate, 
COD_SEGURADO__c, 
COD_STATUS_TRATATIVA__c,
ROW_NUMBER() OVER(PARTITION BY ID ORDER BY LastModifiedDate DESC) R_RNK

FROM `self-service-corp.OW_SFDC_MAIN_PRD.TRATATIVA__c` ) where R_RNK = 1 )


,SEGURADO_AD AS (
SELECT * FROM (
SELECT 
Id, 
LastModifiedDate,
COD_BENEFICIARIO__c,
ROW_NUMBER() OVER(PARTITION BY ID ORDER BY LastModifiedDate desc) R_RNK

FROM `self-service-corp.OW_SFDC_MAIN_PRD.SEGURADO__c`) WHERE R_RNK = 1)

,AD AS (

SELECT 

S.COD_BENEFICIARIO__c,
S_T.COD_TRATATIVA_AD__c,
S_T.FRM_NUM_SENHA_AUTORIZ__c,
T.COD_STATUS_TRATATIVA__c

FROM SOLIC_TRATATIVA_AD S_T
INNER JOIN TRATATIVA T
ON S_T.COD_TRATATIVA_AD__c = T.Id

LEFT JOIN SEGURADO_AD S
ON  S_T.COD_SEGURADO__c = S.Id
AND T.COD_SEGURADO__c = S.Id)

,LIMINAR_SIN AS(
SELECT distinct
COD_ANALITICO_BENEFICIARIO,
FLG_LIMINAR,
NUM_VPP

FROM `self-service-saude.TRU_SAUDE_CONTROLE_PRECO_SINISTRO_PRD.TB_FAT_ITEM_SERVICO_SINISTRO`
where flg_liminar in ('S'))


, cte as(
	SELECT 
	     A.COD_BENEFICIARIO_CHAVE,
       A.COD_CARTEIRINHA_BENEFICIARIO,
       SAUDE.DSC_PROGRAMA_SAUDE_ATIVA_1,
       A.NME_BENEFICIARIO,
       A.NUM_CPF,
       A.COD_PRODUTO,
       A.DSC_PRODUTO,
       A.COD_PLANO,
       A.NME_PLANO,
       A.NME_MUNICIPIO_LOCAL,
       A.SIG_UF_LOCAL,
       A.NUM_CEP_BENEF,
       A.NUM_TELEFONE,
       A.DSC_EMAIL,
       A.DAT_EXCLUSAO,
       A.COD_MOTIVO_EXCLUSAO,
       A.DSC_MOTIVO_EXCLUSAO,
       A.NUM_SOLICITACAO_VPP,
       A.DAT_INCLUSAO,
       A.DAT_SOLICITACAO,
       A.IDC_TIPO_SOLICITACAO,
       A.DSC_TIPO_SOLICITACAO,
       A.COD_PRESTADOR,
       A.NME_FANTASIA,
       A.SIG_UF_PRESTADOR,
       A.MUNICIPIO_PRESTADOR,
       A.NUM_STATUS,
       A.NUM_GUIA_PRESTADOR,
       A.NUM_SOLICITACAO_VPP_REF,
       A.DAT_LIBERACAO_NEGOC,
       A.NUM_DOC_CONTRAT_SOLIC,
       A.IDC_TIPO_DOC_CONTRAT_SOLIC,
       A.NME_CONTRAT_SOLIC,
       A.NME_PROFISSIONAL_SOLIC,
       A.CRM_SOLIC,
       CASE WHEN MEDICO_CC.NUM_CONSELHO IS NULL THEN 'NÃO' ELSE 'SIM' END MEDICO_CC,
       A.DSC_EMAIL_PROF_SOLIC,
       A.NUM_TEL_PROF_SOLIC,
       A.FLG_PREV_USO_QUIMIO,
       CASE WHEN DSC_SERVICO LIKE ('%BIOPSIA%')
            THEN 'S'
            ELSE 'N'
            
            END FLG_BIOPSIA,
       CASE WHEN COD_SERVICO IN (40708128, 64608506, 41001222)
            THEN 'S'
            ELSE 'N'
            
            END FLG_PETCT,
       A.NUM_VPP,
       A.NUM_SOLIC_SP_SADT_ITEM,
       A.NUM_SOLIC_QUIMIO_MEDIC,
       A.NUM_SOLIC_RADIO_ITEM,
       A.NUM_SOLIC_INTERNACAO_ITEM,
       A.COD_SERVICO,
       A.DSC_SERVICO,
       A.DAT_APLICACAO,
       A.DAT_AUT_APLICACAO,
       A.DAT_AUTORIZACAO,
       A.DAT_ATENDIMENTO,
       A.COD_DIAG_IMAGEM_ANS,
       A.DSC_DIAG_IMAGEM,
       A.DAT_REALIZACAO_CIRURGIA,
       A.DSC_CIRURGIA,
       A.DSC_QUIMIOTERAPIA,
       A.DAT_ULTIMA_QUIMIO,
       A.NUM_CAMPO_IRRADIACAO,
       A.NUM_CAMPO_IRRAD_AUTZ,
       A.DSC_AREA_IRRADIADA,
       A.DAT_ULTIMA_RADIO,
       A.COD_ECOG_ANS,
       A.DSC_ECOG,
       A.DAT_DIAGNOSTICO,
       A.DSC_DIAG_CITO_HISTO,
       A.NUM_CICLO_PREVISTO,
       A.NUM_INTERVALO_CICLO,
       A.NUM_CICLO_ATUAL,
       A.FLG_PRIMEIRO_CICLO,
       LS.FLG_LIMINAR,
       A.COD_FINALIDAD_TRAT_ANS,
       A.DSC_FINALIDAD_TRAT,
       A.COD_ESTAD_TUMOR_ANS,
       A.DSC_ESTAD_TUMOR,
       A.DSC_PLANO_TERAPEUTICO,
       A.DSC_OBS_JUSTIFICATIVA_SAS,
       A.CID, 
       CASE 
          WHEN (GI.DSC_STATUS_TRATIVA IN ('FINALIZADO') AND
          GI.DSC_TIPO_FINALIZACAO IN ('COM SUCESSO', 'SEM SUCESSO', 'MONITORAMENTO', 'TRANSFERÊNCIA', 'ÓBITO', 'SEGURADO EXCLUÍDO')) OR DSC_STATUS_TRATIVA IN ('IMPLANTADO AD')
          THEN 'S'

          ELSE 'N'
          end FLG_DESOSPITALIZACAO,
       CASE 
          WHEN AD.COD_STATUS_TRATATIVA__c IN ('Ativo', 'Finalizada', 'Em Andamento')
          THEN 'S'

          ELSE 'N'

          END FLG_ASSIST_DOMIC

       

FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_WRK00_SDCC405_VPP` A
LEFT JOIN CRM_MEDICO_CC MEDICO_CC
ON CAST(A.CRM_SOLIC AS STRING) = MEDICO_CC.NUM_CONSELHO

LEFT JOIN PROGRAMA_SAUDE SAUDE
ON A.COD_BENEFICIARIO_CHAVE = SAUDE.COD_BENEFICIARIO_CHAVE

LEFT JOIN GI GI
ON  A.COD_BENEFICIARIO_CHAVE = GI.COD_BENEFICIARIO__c
AND A.NUM_VPP = GI.FRM_NUM_SENHA_AUTORIZ__c 

LEFT JOIN AD AD
ON  A.COD_BENEFICIARIO_CHAVE = AD.COD_BENEFICIARIO__c
AND A.NUM_VPP = AD.FRM_NUM_SENHA_AUTORIZ__c

LEFT JOIN LIMINAR_SIN LS
ON  A.COD_BENEFICIARIO_CHAVE = LS.COD_ANALITICO_BENEFICIARIO
AND A.NUM_VPP = LS.NUM_VPP

)

select * from cte
