create or replace table `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_EXP_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOSV1_NOB`  AS (


WITH t0 as(
SELECT 
DISTINCT 

CONCAT(COD_PREF_EMPRESA,COD_EMPRESA,SUBSTR(COD_BENEFICIARIO, 5,11)) COD_BENEFICIARIO_CHAVE,
COD_MOTIVO_MANUT,
DAT_EFETIV_EXCLUS,
DAT_MANUT

FROM `self-service-saude.RAW_SAUDE_PRD.BENEFICIARIOS`), 

T1 AS(

select 

A.COD_BENEFICIARIO_CHAVE,
B.COD_CARTEIRINHA_ORIGINAL,
A.COD_MOTIVO_MANUT,
A.DAT_EFETIV_EXCLUS,
A.DAT_MANUT

from T0 A 

INNER JOIN  `self-service-saude.VW_CONS_SAU.DM_MGR_VIDA` B
ON A.COD_BENEFICIARIO_CHAVE = B.COD_BENEFICIARIO_CHAVE
WHERE B.DAT_INICIAL = '2019-01-01')

,T2 AS (

SELECT 
      A.COD_SUFIXO_BENEFICIARIO,
       A.COD_FAMILIAR_BENEFICIARIO,
       A.COD_RDP_BENEFICIARIO,
       A.COD_SISTEMICO_BENEFICIARIO,
       A.COD_ANALITICO_BENEFICIARIO,
       A.COD_DV_BENEFICIARIO,
       A.COD_CARTEIRINHA_BENEFICIARIO,
       A.NME_BENEFICIARIO,
       A.DAT_NASCIMENTO_BENEFICIARIO,
       A.NUM_IDADE_BENEFICIARIO_SINISTRO,
       A.COD_SEXO_BENEFICIARIO,
       A.DSC_SEXO_BENEFICIARIO,
       A.NME_MUNICIPIO_TITULAR_BENEFICIARIO,
       A.NUM_CPF_BENEFICIARIO,
       A.NUM_CPF_TITULAR_BENEFICIARIO,
       A.DSC_SITUACAO_BENEFICIARIO,
       A.SGL_UF_TITULAR_BENEFICIARIO,
       B.DAT_MANUT,
       B.COD_MOTIVO_MANUT,
       B.DAT_EFETIV_EXCLUS,
       A.COD_PLANO,
       A.NME_PLANO,
       A.DSC_CARTEIRA_EMPRESA,
       A.COD_PRESTADOR,
       A.COD_PRINCIPAL_PRESTADOR,
       A.NUM_IDENTIFICACAO_PRINCIPAL_PRESTADOR,
       A.NME_FANTASIA_PRINCIPAL_PRESTADOR,
       A.SGL_UF_PRINCIPAL_PRESTADOR,
       A.NME_MUNICIPIO_PRINCIPAL_PRESTADOR,
       A.NUM_IDENTIFICACAO_PRESTADOR,
       A.NME_FANTASIA_PRESTADOR,
       A.SGL_UF_PRESTADOR,
       A.NME_MUNICIPIO_PRESTADOR,
       A.COD_PRINCIPAL_SERVICO,
       A.DSC_PRINCIPAL_SERVICO,
       A.FLG_ONCOLOGIA,
       A.FLG_INTERNADO_NO_DIA,
       A.FLG_DIAGNOSE_ANALISE_CLINICA,
       A.FLG_DIAGNOSE_IMAGEM,
       A.FLG_DIAGNOSE_OUTRO,
       A.FLG_PROCEDIMENTO,
       A.FLG_TERAPIA_QUIMIOTERAPIA,
       A.FLG_TERAPIA_RADIOTERAPIA,
       A.FLG_MATERIAL,
       A.FLG_MEDICAMENTO,
       A.FLG_PACOTE,
       A.FLG_PS,
       A.FLG_EMERGENCIA,
       A.FLG_INTERNACAO,
       A.COD_PRESTADOR_SOLICITANTE,
       A.NUM_STATUS_SOLICITACAO_VPP,
       A.DSC_STATUS_SOLICITACAO_VPP,
       A.DSC_SITUACAO_QUIMIOTERAPIA_SOLICITACAO_VPP,
       A.DAT_ATENDIMENTO_SOLICITACAO_VPP,
       A.NUM_TIPO_SOLICITACAO_VPP,
       A.COD_TIPO_SOLICITACAO_VPP,
       A.DSC_TIPO_SOLICITACAO_VPP,
       A.DAT_INCLUSAO_SOLICITACAO_VPP,
       A.DAT_INCLUSAO_VPP,
       A.DAT_AUTORIZACAO_VPP,
       A.NUM_SOLICITACAO_VPP,
       A.COD_TIPO_INTERNACAO,
       A.DSC_TIPO_INTERNACAO,
       A.DAT_INTERNACAO,
       A.DSC_CLASSIFICACAO_SINISTRO,
       A.DSC_TIPO_SINISTRO,
       A.DAT_EXECUCAO_SINISTRO,
       A.DAT_INICIO_COBRANCA_SINISTRO,
       A.DAT_FIM_COBRANCA_SINISTRO,
       A.DAT_PAGAMENTO_SINISTRO,
       A.DAT_MES_PAGAMENTO_SINISTRO,
       A.NUM_VPP,
       A.NUM_INTERNACAO,
       A.COD_SERVICO,
       A.DSC_SERVICO,
       A.DSC_GRUPO_SERVICO,
       A.DSC_SUBGRUPO_SERVICO,
       A.COD_ESPECIALIDADE,
       A.NME_ESPECIALIDADE,
       A.COD_TIPO_PRINCIPAL_SERVICO,
       A.DSC_TIPO_PRINCIPAL_SERVICO,
       A.COD_REGIME_INTERNACAO,
       A.DSC_REGIME_INTERNACAO,
       A.DAT_ATENDIMENTO_EFETIVO_SINISTRO,
       A.SGL_TIPO_GUIA_PRESTADOR,
       A.COD_CID_PRINCIPAL_SINISTRO,
       A.DSC_CID_PRINCIPAL_SINISTRO,
       A.COD_PLANO_MIDTICKET,
       A.NME_PLANO_MIDTICKET,
       A.QTD_VPP_INTERCALADA,
       A.QTD_SR_INTERCALADA,
       A.QTD_INTERNACAO,
       A.QTD_DIAS_INTERNADO,
       A.QTD_PAGO_DIARIA,
       A.QTD_DISPONIVEL_DIARIA,
       A.VLR_PAGO_INTERNACAO_REDE,
       A.VLR_PAGO_INTERNACAO_REEMBOLSO,
       A.VLR_PAGO_INTERNACAO_TOTAL,
       A.QTD_SERVICO_PAGO,
       A.VLR_APRESENTADO_SERVICO,
       A.VLR_PAGO_SERVICO,
       A.QTD_CONSULTA,
       A.VLR_PAGO_ATENDIMENTO_TOTAL,
       A.QTD_BIOPSIAS,
       A.QTD_PET,
       A.QTD_QUIMIO,
       A.MED_QUIMIO,
       A.QTD_RADIO,
       A.MED_RADIO,
       A.QTD_INTER_ELET,
       A.MED_INTER_ELET,
       A.QTD_INTER_CLIN,
       A.MED_INTER_CLIN,
       A.QTD_INTER_UTI,
       A.MED_INTER_UTI,
       A.QTD_PS,
       A.MED_PS,
       A.QTD_INTER_CIRUR,
       A.MED_INTER_CIRUR

FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_EXP_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOSV1`  A
INNER JOIN T1 B
ON A.COD_CARTEIRINHA_BENEFICIARIO = B.COD_CARTEIRINHA_ORIGINAL)
, T3 AS (
SELECT DISTINCT COD_CARTEIRINHA_BENEFICIARIO FROM T2
WHERE COD_MOTIVO_MANUT NOT IN (5,19))

SELECT A.* FROM T2 A
INNER JOIN T3 B
ON A.COD_CARTEIRINHA_BENEFICIARIO = B.COD_CARTEIRINHA_BENEFICIARIO)