tb_exxp_classes_sinistro_analise

 CREATE OR REPLACE TABLE `self-service-saude.VW_CONS_SAU.TB_EXP_CLASSES_SINISTRO_ANALISE` AS

WITH CTE_SIN_1 AS(
SELECT 
T1.COD_BENEFICIARIO_CHAVE 
      ,T1.VAL_SINISTRO
      ,T1.FLG_TIPO_EMERGENCIA
      ,T2.DSC_GRUPO_SERVICO
      ,CONCAT(CAST(EXTRACT(YEAR FROM T1.DAT_EXECUCAO) AS STRING),CAST(EXTRACT(MONTH FROM T1.DAT_EXECUCAO) AS STRING)) AS ANO_MES
  FROM `self-service-saude.VW_CONS_SAU.DM_MGR_SINISTRO` T1
  LEFT JOIN  `self-service-saude.VW_CONS_SAU.TB_DIM_SERVICO` T2
    ON T1.COD_SERVICO = T2.COD_SERVICO 
 WHERE T1.DAT_EXECUCAO >= '2017-01-01'
   AND T1.DAT_EXECUCAO <= DATE_TRUNC(DATE_SUB(CURRENT_DATE,INTERVAL 1 MONTH),MONTH)
--   AND T1.COD_BENEFICIARIO_CHAVE = '7865700006400010'
)--SELECT * FROM CTE_SIN_1
,CTE_SIN_2 AS (
SELECT T1.COD_BENEFICIARIO_CHAVE
      ,T1.VAL_SINISTRO
      ,T1.FLG_TIPO_EMERGENCIA      
      ,T1.DSC_GRUPO_SERVICO
      ,CAST(CASE WHEN ANO_MES IN ('20171','20172','20173')
            THEN '1'
            WHEN ANO_MES IN ('20174','20175','20176')
            THEN '2'
            WHEN ANO_MES IN ('20177','20178','20179')
            THEN '3'
            WHEN ANO_MES IN ('201710','201711','201712')
            THEN '4'
            WHEN ANO_MES IN ('20181','20182','20183')
            THEN '5'
            WHEN ANO_MES IN ('20184','20185','20186')
            THEN '6'
            WHEN ANO_MES IN ('20187','20188','20189')
            THEN '7'
            WHEN ANO_MES IN ('201810','201811','201812')
            THEN '8'
            WHEN ANO_MES IN ('20191','20192','20193')
            THEN '9'
            WHEN ANO_MES IN ('20194','20195','20196')
            THEN '10'
            WHEN ANO_MES IN ('20197','20198','20199')
            THEN '11'
            WHEN ANO_MES IN ('201910','201911','201912')
            THEN '12'
            ELSE '0' 
         END AS NUMERIC) AS COD_TRIMESTRE
  FROM CTE_SIN_1 T1      
 )
,CTE_SIN_3 AS (
SELECT T1.*
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'DIAGNOSE'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_DIAGNOSE_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'CONSULTA'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_CONSULTA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'DIARIAS'         ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_DIARIAS_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'NÃO CLASSIFICADO',ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_NAO_CLASSIFICADO_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'TAXA'            ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_TAXA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'MEDICAMENTO'     ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_MEDICAMENTO_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PRÓTESE'         ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PROTESE_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'ENDODONTIA'      ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_ENDODONTIA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PERIODONTIA'     ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PERIODONTIA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'TAXA DE SALA'    ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_TAXA_SALA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'IMAGEM'          ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_IMAGEM_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'ORTODONTIA'      ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_ORTODONTIA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'REMOCAO'         ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_REMOCAO_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'MATERIAL'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_MATERIAL_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'CIRURGIA'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_CIRURGIA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'ODONTOLOGIA'     ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_ODONTOLOGIA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PROCEDIMENTO'    ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PROCEDIMENTO_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'TERAPIA'         ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_TERAPIA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'NORMAL'          ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_NORMAL_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'GASOTERAPIA'     ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_GASOTERAPIA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PREVENÇÃO'       ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PREVENCAO_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'DENTÍSTICA'      ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_DENTISTICA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'VACINA'          ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_VACINA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PACOTE'          ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PACOTE_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'ODONTOPEDIATRIA' ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_ODONTOPEDIATRIA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'COMPLEMENTAR'    ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_COMPLEMENTAR_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'CHECK UP'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_CHECKUP_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'CONTRASTES'      ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_CONTRASTES_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PROGRAMAS'       ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PROGRAMAS_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'DIETA'           ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_DIETA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'JUDICIAL'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_JUDICIAL_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'IMPLANTES'       ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_IMPLANTES_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA = 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'EMERGÊNCIA'      ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_EMERGENCIA_ELETIVA
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'DIAGNOSE'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_DIAGNOSE_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'CONSULTA'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_CONSULTA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'DIARIAS'         ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_DIARIAS_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'NÃO CLASSIFICADO',ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_NAO_CLASSIFICADO_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'TAXA'            ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_TAXA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'MEDICAMENTO'     ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_MEDICAMENTO_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PRÓTESE'         ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PROTESE_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'ENDODONTIA'      ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_ENDODONTIA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PERIODONTIA'     ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PERIODONTIA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'TAXA DE SALA'    ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_TAXA_SALA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'IMAGEM'          ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_IMAGEM_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'ORTODONTIA'      ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_ORTODONTIA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'REMOCAO'         ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_REMOCAO_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'MATERIAL'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_MATERIAL_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'CIRURGIA'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_CIRURGIA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'ODONTOLOGIA'     ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_ODONTOLOGIA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PROCEDIMENTO'    ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PROCEDIMENTO_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'TERAPIA'         ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_TERAPIA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'NORMAL'          ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_NORMAL_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'GASOTERAPIA'     ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_GASOTERAPIA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PREVENÇÃO'       ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PREVENCAO_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'DENTÍSTICA'      ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_DENTISTICA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'VACINA'          ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_VACINA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PACOTE'          ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PACOTE_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'ODONTOPEDIATRIA' ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_ODONTOPEDIATRIA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'COMPLEMENTAR'    ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_COMPLEMENTAR_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'CHECK UP'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_CHECKUP_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'CONTRASTES'      ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_CONTRASTES_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'PROGRAMAS'       ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_PROGRAMAS_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'DIETA'           ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_DIETA_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'JUDICIAL'        ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_JUDICIAL_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'IMPLANTES'       ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_IMPLANTES_PS
      ,IF(FLG_TIPO_EMERGENCIA <> 'N' AND TRIM(DSC_GRUPO_SERVICO) = 'EMERGÊNCIA'      ,ROUND(SUM(VAL_SINISTRO),2),0) AS VAL_SINISTRO_EMERGENCIA_PS      
  FROM `self-service-saude.VW_CONS_SAU.TB_EXP_CLASSES_SINISTRO_TOP` T1
  LEFT JOIN CTE_SIN_2 T2
    ON T1.COD_BENEFICIARIO_CHAVE = T2.COD_BENEFICIARIO_CHAVE
   AND T1.TRI                    = T2.COD_TRIMESTRE
--  WHERE T1.COD_BENEFICIARIO_CHAVE = '7865700006400010'   
  GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,FLG_TIPO_EMERGENCIA,DSC_GRUPO_SERVICO
 --ORDER BY TRI
)
SELECT COD_BENEFICIARIO
      ,TRI
      ,COD_APRESENTACAO_EMPRESA
      ,COD_BENEFICIARIO_CHAVE
      ,IDC_TIPO_PLANO
      ,DSC_SEXO
      ,DSC_CARTEIRA
      ,DAT_NASCIMENTO
      ,DSC_SITUACAO_TITULAR
      ,DSC_EST_CIVIL
      ,QTD_ATIVO
      ,VAL_CLS
      ,VAL_AMB
      ,VAL_INTER
      ,QTD_INTER
      ,CEM_17_ANO
      ,CEM_18_ANO
      ,CEM_19_ANO
      ,CEM_TRI
      ,COORTE1
      ,COORTE2
      ,COORTE3
      ,COORTE4
     ,ROUND(SUM(VAL_SINISTRO_DIAGNOSE_ELETIVA),2) AS             VAL_SINISTRO_DIAGNOSE_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_CONSULTA_ELETIVA),2) AS             VAL_SINISTRO_CONSULTA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_DIARIAS_ELETIVA),2) AS              VAL_SINISTRO_DIARIAS_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_NAO_CLASSIFICADO_ELETIVA),2) AS     VAL_SINISTRO_NAO_CLASSIFICADO_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_TAXA_ELETIVA),2) AS                 VAL_SINISTRO_TAXA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_MEDICAMENTO_ELETIVA),2) AS          VAL_SINISTRO_MEDICAMENTO_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_PROTESE_ELETIVA),2) AS              VAL_SINISTRO_PROTESE_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_ENDODONTIA_ELETIVA),2) AS           VAL_SINISTRO_ENDODONTIA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_PERIODONTIA_ELETIVA),2) AS          VAL_SINISTRO_PERIODONTIA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_TAXA_SALA_ELETIVA),2) AS            VAL_SINISTRO_TAXA_SALA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_IMAGEM_ELETIVA),2) AS               VAL_SINISTRO_IMAGEM_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_ORTODONTIA_ELETIVA),2) AS           VAL_SINISTRO_ORTODONTIA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_REMOCAO_ELETIVA),2) AS              VAL_SINISTRO_REMOCAO_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_MATERIAL_ELETIVA),2) AS             VAL_SINISTRO_MATERIAL_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_CIRURGIA_ELETIVA),2) AS             VAL_SINISTRO_CIRURGIA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_ODONTOLOGIA_ELETIVA),2) AS          VAL_SINISTRO_ODONTOLOGIA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_PROCEDIMENTO_ELETIVA),2) AS         VAL_SINISTRO_PROCEDIMENTO_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_TERAPIA_ELETIVA),2) AS              VAL_SINISTRO_TERAPIA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_NORMAL_ELETIVA),2) AS               VAL_SINISTRO_NORMAL_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_GASOTERAPIA_ELETIVA),2) AS          VAL_SINISTRO_GASOTERAPIA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_PREVENCAO_ELETIVA),2) AS            VAL_SINISTRO_PREVENCAO_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_DENTISTICA_ELETIVA),2) AS           VAL_SINISTRO_DENTISTICA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_VACINA_ELETIVA),2) AS               VAL_SINISTRO_VACINA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_PACOTE_ELETIVA),2) AS               VAL_SINISTRO_PACOTE_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_ODONTOPEDIATRIA_ELETIVA),2) AS      VAL_SINISTRO_ODONTOPEDIATRIA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_COMPLEMENTAR_ELETIVA),2) AS         VAL_SINISTRO_COMPLEMENTAR_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_CHECKUP_ELETIVA),2) AS              VAL_SINISTRO_CHECKUP_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_CONTRASTES_ELETIVA),2) AS           VAL_SINISTRO_CONTRASTES_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_PROGRAMAS_ELETIVA),2) AS            VAL_SINISTRO_PROGRAMAS_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_DIETA_ELETIVA),2) AS                VAL_SINISTRO_DIETA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_JUDICIAL_ELETIVA),2) AS             VAL_SINISTRO_JUDICIAL_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_IMPLANTES_ELETIVA),2) AS            VAL_SINISTRO_IMPLANTES_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_EMERGENCIA_ELETIVA),2) AS           VAL_SINISTRO_EMERGENCIA_ELETIVA
     ,ROUND(SUM(VAL_SINISTRO_DIAGNOSE_PS),2) AS             VAL_SINISTRO_DIAGNOSE_PS
     ,ROUND(SUM(VAL_SINISTRO_CONSULTA_PS),2) AS             VAL_SINISTRO_CONSULTA_PS
     ,ROUND(SUM(VAL_SINISTRO_DIARIAS_PS),2) AS              VAL_SINISTRO_DIARIAS_PS
     ,ROUND(SUM(VAL_SINISTRO_NAO_CLASSIFICADO_PS),2) AS     VAL_SINISTRO_NAO_CLASSIFICADO_PS
     ,ROUND(SUM(VAL_SINISTRO_TAXA_PS),2) AS                 VAL_SINISTRO_TAXA_PS
     ,ROUND(SUM(VAL_SINISTRO_MEDICAMENTO_PS),2) AS          VAL_SINISTRO_MEDICAMENTO_PS
     ,ROUND(SUM(VAL_SINISTRO_PROTESE_PS),2) AS              VAL_SINISTRO_PROTESE_PS
     ,ROUND(SUM(VAL_SINISTRO_ENDODONTIA_PS),2) AS           VAL_SINISTRO_ENDODONTIA_PS
     ,ROUND(SUM(VAL_SINISTRO_PERIODONTIA_PS),2) AS          VAL_SINISTRO_PERIODONTIA_PS
     ,ROUND(SUM(VAL_SINISTRO_TAXA_SALA_PS),2) AS            VAL_SINISTRO_TAXA_SALA_PS
     ,ROUND(SUM(VAL_SINISTRO_IMAGEM_PS),2) AS               VAL_SINISTRO_IMAGEM_PS
     ,ROUND(SUM(VAL_SINISTRO_ORTODONTIA_PS),2) AS           VAL_SINISTRO_ORTODONTIA_PS
     ,ROUND(SUM(VAL_SINISTRO_REMOCAO_PS),2) AS              VAL_SINISTRO_REMOCAO_PS
     ,ROUND(SUM(VAL_SINISTRO_MATERIAL_PS),2) AS             VAL_SINISTRO_MATERIAL_PS
     ,ROUND(SUM(VAL_SINISTRO_CIRURGIA_PS),2) AS             VAL_SINISTRO_CIRURGIA_PS
     ,ROUND(SUM(VAL_SINISTRO_ODONTOLOGIA_PS),2) AS          VAL_SINISTRO_ODONTOLOGIA_PS
     ,ROUND(SUM(VAL_SINISTRO_PROCEDIMENTO_PS),2) AS         VAL_SINISTRO_PROCEDIMENTO_PS
     ,ROUND(SUM(VAL_SINISTRO_TERAPIA_PS),2) AS              VAL_SINISTRO_TERAPIA_PS
     ,ROUND(SUM(VAL_SINISTRO_NORMAL_PS),2) AS               VAL_SINISTRO_NORMAL_PS
     ,ROUND(SUM(VAL_SINISTRO_GASOTERAPIA_PS),2) AS          VAL_SINISTRO_GASOTERAPIA_PS
     ,ROUND(SUM(VAL_SINISTRO_PREVENCAO_PS),2) AS            VAL_SINISTRO_PREVENCAO_PS
     ,ROUND(SUM(VAL_SINISTRO_DENTISTICA_PS),2) AS           VAL_SINISTRO_DENTISTICA_PS
     ,ROUND(SUM(VAL_SINISTRO_VACINA_PS),2) AS               VAL_SINISTRO_VACINA_PS
     ,ROUND(SUM(VAL_SINISTRO_PACOTE_PS),2) AS               VAL_SINISTRO_PACOTE_PS
     ,ROUND(SUM(VAL_SINISTRO_ODONTOPEDIATRIA_PS),2) AS      VAL_SINISTRO_ODONTOPEDIATRIA_PS
     ,ROUND(SUM(VAL_SINISTRO_COMPLEMENTAR_PS),2) AS         VAL_SINISTRO_COMPLEMENTAR_PS
     ,ROUND(SUM(VAL_SINISTRO_CHECKUP_PS),2) AS              VAL_SINISTRO_CHECKUP_PS
     ,ROUND(SUM(VAL_SINISTRO_CONTRASTES_PS),2) AS           VAL_SINISTRO_CONTRASTES_PS
     ,ROUND(SUM(VAL_SINISTRO_PROGRAMAS_PS),2) AS            VAL_SINISTRO_PROGRAMAS_PS
     ,ROUND(SUM(VAL_SINISTRO_DIETA_PS),2) AS                VAL_SINISTRO_DIETA_PS
     ,ROUND(SUM(VAL_SINISTRO_JUDICIAL_PS),2) AS             VAL_SINISTRO_JUDICIAL_PS
     ,ROUND(SUM(VAL_SINISTRO_IMPLANTES_PS),2) AS            VAL_SINISTRO_IMPLANTES_PS
     ,ROUND(SUM(VAL_SINISTRO_EMERGENCIA_PS),2) AS           VAL_SINISTRO_EMERGENCIA_PS
  FROM CTE_SIN_3
 GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23