 -- TB_EXP_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOS

 create or replace table `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_EXP_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOS` AS
 
 WITH TB_405 AS (SELECT 
COD_CARTEIRINHA_BENEFICIARIO,
COD_SERVICO,
DE_PARA,
VLR_PAGO_SERVICO
,
row_number() over(partition by COD_CARTEIRINHA_BENEFICIARIO, de_para) R_RNK


FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_WRK02_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOS` 
-- WHERE DATE_TRUNC(DAT_EXECUCAO_SINISTRO, MONTH) BETWEEN '2017-01-01' AND '2020-06-01'
 ),

 TB_BIOPSIA AS
   (
       SELECT 
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
       SUM(CASE 
           WHEN DE_PARA IN ('BIOPSIA') THEN 1 ELSE 0 
                     END) QTD_BIOPSIAS
       FROM TB_405

       GROUP BY 1,2),

--CONTAGEM DE PET CT
TB_PET AS 
(
       SELECT 
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
       SUM(CASE 
           WHEN DE_PARA IN ('PET_CT') THEN 1 ELSE 0 
                     END) QTD_PET
       FROM TB_405
GROUP BY 1,2
),

--QTD QUIMIO E CUSTO

TB_QUIMIO AS 
(

       SELECT
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
    QTD_QUIMIO,
       safe_divide(SUM(VLR_QUIMIO),SUM(QTD_QUIMIO)) MED_QUIMIO
       FROM (

SELECT 
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
       SUM(CASE 
           WHEN DE_PARA IN ('QUIMIOTERAPIA') THEN 1 ELSE 0 
                     END) QTD_QUIMIO,
       SUM(CASE
              WHEN DE_PARA IN ('QUIMIOTERAPIA') THEN VLR_PAGO_SERVICO ELSE 0 
                            END) VLR_QUIMIO
       FROM TB_405
GROUP BY 1,2)
       GROUP BY 1,2,3
),

--qtd radioterapias e custo
TB_RADIO AS 
(

       SELECT
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
    QTD_RADIO,
       safe_divide(SUM(VLR_RADIO),SUM(QTD_RADIO)) MED_RADIO
       FROM (

SELECT 
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
       SUM(CASE 
           WHEN DE_PARA IN ('RADIOTERAPIA') THEN 1 ELSE 0 
                     END) QTD_RADIO,
       SUM(CASE
              WHEN DE_PARA IN ('RADIOTERAPIA') THEN VLR_PAGO_SERVICO ELSE 0 
                            END) VLR_RADIO
       FROM TB_405
GROUP BY 1,2)
       GROUP BY 1,2,3
),

--QTD INTERNACAO ELETIVA E CUSTO

TB_INTER_ELET AS (

       SELECT
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
    QTD_INTER_ELET,
       safe_divide(SUM(VLR_INTER_ELET),SUM(QTD_INTER_ELET)) MED_INTER_ELET
       FROM (

SELECT 
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
       SUM(CASE 
           WHEN DE_PARA IN ('INTERNACAO_ELETIVA') THEN 1 ELSE 0 
                     END) QTD_INTER_ELET,
       SUM(CASE
              WHEN DE_PARA IN ('INTERNACAO_ELETIVA') THEN VLR_PAGO_SERVICO ELSE 0 
                            END) VLR_INTER_ELET
       FROM TB_405
GROUP BY 1,2)
       GROUP BY 1,2,3
),

--QTD_INTERNACAO CLINICA E CUSTO
TB_INTER_CLIN AS
(
       SELECT
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
    QTD_INTER_CLIN,
       safe_divide(SUM(VLR_INTER_CLIN),SUM(QTD_INTER_CLIN)) MED_INTER_CLIN
       FROM (

SELECT 
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
       SUM(CASE 
           WHEN DE_PARA IN ('INTERNACAO_CLINICA') THEN 1 ELSE 0 
                     END) QTD_INTER_CLIN,
       SUM(CASE
              WHEN DE_PARA IN ('INTERNACAO_CLINICA') THEN VLR_PAGO_SERVICO ELSE 0 
                            END) VLR_INTER_CLIN
       FROM TB_405
GROUP BY 1,2)
       GROUP BY 1,2,3
),

--QTD INTERNACAO UTI E CUSTO

TB_INTER_UTI AS
(
       SELECT
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
    QTD_INTER_UTI,
       safe_divide(SUM(VLR_INTER_UTI),SUM(QTD_INTER_UTI)) MED_INTER_UTI
       FROM (

SELECT 
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
       SUM(CASE 
           WHEN DE_PARA IN ('INTERNACAO_UTI') THEN 1 ELSE 0 
                     END) QTD_INTER_UTI,
       SUM(CASE
              WHEN DE_PARA IN ('INTERNACAO_UTI') THEN VLR_PAGO_SERVICO ELSE 0 
                            END) VLR_INTER_UTI
       FROM TB_405
GROUP BY 1,2)
       GROUP BY 1,2,3
),

--PASSAGEM PS E CUSTO

TB_PASSAGEM_PS AS 
(

       SELECT
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
    QTD_PS,
       safe_divide(SUM(VLR_PS),SUM(QTD_PS)) MED_PS
       FROM (

SELECT 
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
       SUM(CASE 
           WHEN DE_PARA IN ('PASSAGEM_PS') THEN 1 ELSE 0 
                     END) QTD_PS,
       SUM(CASE
              WHEN DE_PARA IN ('PASSAGEM_PS') THEN VLR_PAGO_SERVICO ELSE 0 
                            END) VLR_PS
       FROM TB_405
GROUP BY 1,2)
       GROUP BY 1,2,3
),

--internacao cirurgica e custo
TB_INTER_CIRUR AS 
(
       SELECT
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
    QTD_INTER_CIRUR,
       safe_divide(SUM(VLR_INTER_CIRUR),SUM(QTD_INTER_CIRUR)) MED_INTER_CIRUR
       FROM (

SELECT 
       COD_CARTEIRINHA_BENEFICIARIO,
       DE_PARA,
       SUM(CASE 
           WHEN DE_PARA IN ('INTERNACAO_CIRURGICA') THEN 1 ELSE 0 
                     END) QTD_INTER_CIRUR,
       SUM(CASE
              WHEN DE_PARA IN ('INTERNACAO_CIRURGICA') THEN VLR_PAGO_SERVICO ELSE 0 
                            END) VLR_INTER_CIRUR
       FROM TB_405
GROUP BY 1,2)
       GROUP BY 1,2,3),


TB_01 AS (


SELECT distinct 

       A.*,
       B.QTD_BIOPSIAS,
       C.QTD_PET,
       D.QTD_QUIMIO,
       D.MED_QUIMIO,
       E.QTD_RADIO,
       E.MED_RADIO,
       F.QTD_INTER_ELET,
       F.MED_INTER_ELET,
       G.QTD_INTER_CLIN,
       G.MED_INTER_CLIN,
       H.QTD_INTER_UTI,
       H.MED_INTER_UTI,
       I.QTD_PS,
       I.MED_PS,
       J.QTD_INTER_CIRUR,
       J.MED_INTER_CIRUR








 FROM  TB_405 A
       LEFT JOIN TB_BIOPSIA B
       ON  A.COD_CARTEIRINHA_BENEFICIARIO = B.COD_CARTEIRINHA_BENEFICIARIO
       AND A.DE_PARA = B.DE_PARA
       AND A.R_RNK = 1

       LEFT JOIN TB_PET C
       ON  A.COD_CARTEIRINHA_BENEFICIARIO = C.COD_CARTEIRINHA_BENEFICIARIO
       AND A.DE_PARA = C.DE_PARA
       AND A.R_RNK = 1

       LEFT JOIN TB_QUIMIO D
       ON  A.COD_CARTEIRINHA_BENEFICIARIO = D.COD_CARTEIRINHA_BENEFICIARIO
       AND A.DE_PARA = D.DE_PARA
       AND A.R_RNK = 1

       LEFT JOIN TB_RADIO E
      ON  A.COD_CARTEIRINHA_BENEFICIARIO = E.COD_CARTEIRINHA_BENEFICIARIO
       AND A.DE_PARA = E.DE_PARA
       AND A.R_RNK = 1

       LEFT JOIN TB_INTER_ELET F
       ON  A.COD_CARTEIRINHA_BENEFICIARIO = F.COD_CARTEIRINHA_BENEFICIARIO
       AND A.DE_PARA = F.DE_PARA
       AND A.R_RNK = 1

       LEFT JOIN TB_INTER_CLIN G
       ON  A.COD_CARTEIRINHA_BENEFICIARIO = G.COD_CARTEIRINHA_BENEFICIARIO
       AND A.DE_PARA = G.DE_PARA
       AND A.R_RNK = 1

       LEFT JOIN TB_INTER_UTI H
       ON  A.COD_CARTEIRINHA_BENEFICIARIO = H.COD_CARTEIRINHA_BENEFICIARIO
       AND A.DE_PARA = H.DE_PARA
       AND A.R_RNK = 1

       LEFT JOIN TB_PASSAGEM_PS I
       ON  A.COD_CARTEIRINHA_BENEFICIARIO = I.COD_CARTEIRINHA_BENEFICIARIO
       AND A.DE_PARA = I.DE_PARA
       AND A.R_RNK = 1

       LEFT JOIN TB_INTER_CIRUR J
       ON  A.COD_CARTEIRINHA_BENEFICIARIO = J.COD_CARTEIRINHA_BENEFICIARIO
       AND A.DE_PARA = J.DE_PARA
       AND A.R_RNK = 1
       ),


 TB_02 AS ( 
  SELECT 
       A.*,
       B.QTD_BIOPSIAS,
       B.QTD_PET,
       B.QTD_QUIMIO,
       B.MED_QUIMIO,
       B.QTD_RADIO,
       B.MED_RADIO,
       B.QTD_INTER_ELET,
       B.MED_INTER_ELET,
       B.QTD_INTER_CLIN,
       B.MED_INTER_CLIN,
       B.QTD_INTER_UTI,
       B.MED_INTER_UTI,
       B.QTD_PS,
       B.MED_PS,
       B.QTD_INTER_CIRUR,
       B.MED_INTER_CIRUR

  FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_WRK02_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOS` A
  LEFT JOIN TB_01 B
  ON  A.COD_CARTEIRINHA_BENEFICIARIO = B.COD_CARTEIRINHA_BENEFICIARIO
  AND A.DE_PARA = B.DE_PARA
  AND B.R_RNK = 1
  ),
  
  TB_03 AS(
  
  SELECT DISTINCT COD_ANALITICO_BENEFICIARIO FROM TB_02),
  
  TB_04 AS (
  SELECT 
  COD_ANALITICO_BENEFICIARIO,
  MIN(DAT_MIN_EXECUCAO_SINISTRO) DAT_MIN_EXECUCAO_SINISTRO
  FROM (
  

SELECT DISTINCT 

A.COD_ANALITICO_BENEFICIARIO, 
B.COD_SERVICO, 
MIN(B.DAT_EXECUCAO_SINISTRO) DAT_MIN_EXECUCAO_SINISTRO  

FROM TB_03 A
INNER JOIN `self-service-saude.TRU_SAUDE_CONTROLE_PRECO_SINISTRO_PRD.TB_FAT_ITEM_SERVICO_SINISTRO` B
ON A.COD_ANALITICO_BENEFICIARIO = B.COD_ANALITICO_BENEFICIARIO

WHERE B.COD_SERVICO IN (SELECT COD_SERVICOS
                               FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_COD_SERVICOS`)
                               

GROUP BY 1,2) GROUP BY 1), T_BASE_FINAL AS (
-- WHERE DATE_TRUNC(DAT_EXECUCAO_SINISTRO, MONTH) BETWEEN '2017-01-01' AND '2020-06-01'

--1095883
SELECT * EXCEPT(DE_PARA) FROM (
SELECT 
  A.*,
  B.DAT_MIN_EXECUCAO_SINISTRO
  

FROM TB_02  A
LEFT JOIN TB_04 B
ON A.COD_ANALITICO_BENEFICIARIO = B.COD_ANALITICO_BENEFICIARIO)),

OBITO AS (

SELECT DISTINCT
COD_ANALITICO_BENEFICIARIO,
DAT_EXCLUSAO_OPERACIONAL DAT_EXCLUS,
COD_MOTIVO_EXCLUSAO,
DSC_MOTIVO_EXCLUSAO

FROM `self-service-saude.TRU_SAUDE_OPERACAO_PRD.TB_CAD_BENEFICIARIO` )




SELECT  
       A.COD_DOCUMENTO_SINISTRO,
       A.COD_COMPLEMENTO_SINISTRO,
       A.COD_SEQUENCIA_SINISTRO,
       A.COD_ITEM_SERVICO_SINISTRO,
       A.COD_ANEXO_ITEM_SERVICO_SINISTRO,
       A.COD_SUFIXO_BENEFICIARIO,
       A.COD_FAMILIAR_BENEFICIARIO,
       A.COD_RDP_BENEFICIARIO,
       A.COD_SISTEMICO_BENEFICIARIO,
       A.COD_ANALITICO_BENEFICIARIO,
       A.COD_DV_BENEFICIARIO,
       A.COD_CARTEIRINHA_BENEFICIARIO,
       A.NME_BENEFICIARIO,
       A.DAT_NASCIMENTO_BENEFICIARIO,
       A.NUM_IDADE_BENEFICIARIO_SINISTRO,
       A.COD_SEXO_BENEFICIARIO,
       A.DSC_SEXO_BENEFICIARIO,
       A.NME_MUNICIPIO_TITULAR_BENEFICIARIO,
       A.NUM_CPF_BENEFICIARIO,
       A.NUM_CPF_TITULAR_BENEFICIARIO,
       A.DSC_SITUACAO_BENEFICIARIO,
       A.SGL_UF_TITULAR_BENEFICIARIO,
       B.DAT_EXCLUS,
       B.COD_MOTIVO_EXCLUSAO,
       B.DSC_MOTIVO_EXCLUSAO,
       A.COD_PLANO,
       A.NME_PLANO,
       A.DSC_CARTEIRA_EMPRESA,
       A.COD_PRESTADOR,
       A.COD_PRINCIPAL_PRESTADOR,
       A.NUM_IDENTIFICACAO_PRINCIPAL_PRESTADOR,
       A.NME_FANTASIA_PRINCIPAL_PRESTADOR,
       A.SGL_UF_PRINCIPAL_PRESTADOR,
       A.NME_MUNICIPIO_PRINCIPAL_PRESTADOR,
       A.NUM_IDENTIFICACAO_PRESTADOR,
       A.NME_FANTASIA_PRESTADOR,
       A.SGL_UF_PRESTADOR,
       A.NME_MUNICIPIO_PRESTADOR,
       A.COD_PRINCIPAL_SERVICO,
       A.DSC_PRINCIPAL_SERVICO,
       CASE A.COD_PRINCIPAL_SERVICO WHEN  30010004
               THEN 'S'
               ELSE 'N'
               END AS FLG_INTERNACAO_ONCOLOGICA,
       A.FLG_ONCOLOGIA,
       A.FLG_INTERNADO_NO_DIA,
       A.FLG_DIAGNOSE_ANALISE_CLINICA,
       A.FLG_DIAGNOSE_IMAGEM,
       A.FLG_DIAGNOSE_OUTRO,
       A.FLG_PROCEDIMENTO,
       A.FLG_TERAPIA_QUIMIOTERAPIA,
       A.FLG_TERAPIA_RADIOTERAPIA,
       A.FLG_MATERIAL,
       A.FLG_MEDICAMENTO,
       A.FLG_PACOTE,
       A.FLG_PS,
       A.FLG_EMERGENCIA,
       A.FLG_INTERNACAO,
       A.COD_PRESTADOR_SOLICITANTE,
       A.NUM_STATUS_SOLICITACAO_VPP,
       A.DSC_STATUS_SOLICITACAO_VPP,
       A.DSC_SITUACAO_QUIMIOTERAPIA_SOLICITACAO_VPP,
       A.DAT_ATENDIMENTO_SOLICITACAO_VPP,
       A.NUM_TIPO_SOLICITACAO_VPP,
       A.COD_TIPO_SOLICITACAO_VPP,
       A.DSC_TIPO_SOLICITACAO_VPP,
       A.DAT_INCLUSAO_SOLICITACAO_VPP,
       A.DAT_INCLUSAO_VPP,
       A.DAT_AUTORIZACAO_VPP,
       A.NUM_SOLICITACAO_VPP,
       A.COD_TIPO_INTERNACAO,
       A.DSC_TIPO_INTERNACAO,
       A.DAT_INTERNACAO,
       A.DSC_CLASSIFICACAO_SINISTRO,
       A.DSC_TIPO_SINISTRO,
       A.DAT_EXECUCAO_SINISTRO,
       A.DAT_INICIO_COBRANCA_SINISTRO,
       A.DAT_FIM_COBRANCA_SINISTRO,
       A.DAT_PAGAMENTO_SINISTRO,
       A.DAT_MES_PAGAMENTO_SINISTRO,
       A.NUM_VPP,
       A.NUM_INTERNACAO,
       A.COD_SERVICO,
       A.DSC_SERVICO,
       A.DSC_GRUPO_SERVICO,
       A.DSC_SUBGRUPO_SERVICO,
       A.COD_ESPECIALIDADE,
       A.NME_ESPECIALIDADE,
       A.COD_TIPO_PRINCIPAL_SERVICO,
       A.DSC_TIPO_PRINCIPAL_SERVICO,
       A.COD_REGIME_INTERNACAO,
       A.DSC_REGIME_INTERNACAO,
       A.DAT_ATENDIMENTO_EFETIVO_SINISTRO,
       A.SGL_TIPO_GUIA_PRESTADOR,
       A.COD_CID_PRINCIPAL_SINISTRO,
       A.DSC_CID_PRINCIPAL_SINISTRO,
       A.COD_PLANO_MIDTICKET,
       A.NME_PLANO_MIDTICKET,
       A.QTD_VPP_INTERCALADA,
       A.QTD_SR_INTERCALADA,
       A.QTD_INTERNACAO,
       A.QTD_DIAS_INTERNADO,
       A.QTD_PAGO_DIARIA,
       A.QTD_DISPONIVEL_DIARIA,
       A.VLR_PAGO_INTERNACAO_REDE,
       A.VLR_PAGO_INTERNACAO_REEMBOLSO,
       A.VLR_PAGO_INTERNACAO_TOTAL,
       A.QTD_SERVICO_PAGO,
       A.VLR_APRESENTADO_SERVICO,
       A.VLR_PAGO_SERVICO,
       A.QTD_CONSULTA,
       A.VLR_PAGO_ATENDIMENTO_TOTAL,
       A.QTD_BIOPSIAS,
       A.QTD_PET,
       A.QTD_QUIMIO,
       A.MED_QUIMIO,
       A.QTD_RADIO,
       A.MED_RADIO,
       A.QTD_INTER_ELET,
       A.MED_INTER_ELET,
       A.QTD_INTER_CLIN,
       A.MED_INTER_CLIN,
       A.QTD_INTER_UTI,
       A.MED_INTER_UTI,
       A.QTD_PS,
       A.MED_PS,
       A.QTD_INTER_CIRUR,
       A.MED_INTER_CIRUR,
       A.DAT_MIN_EXECUCAO_SINISTRO



FROM T_BASE_FINAL A
INNER JOIN OBITO B 
ON A.COD_ANALITICO_BENEFICIARIO = B.COD_ANALITICO_BENEFICIARIO

