create or replace table `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_WRK02_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOS` as
WITH T1 AS (SELECT DISTINCT
COD_ANALITICO_BENEFICIARIO,
COD_CARTEIRINHA_BENEFICIARIO,
DE_PARA,
COD_SERVICO
FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_WRK01_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOS`),


TB_405 AS (SELECT 
  A.*,
	B.DE_PARA
	FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_WRK00_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOS` A
	LEFT JOIN T1 B
	ON  A.COD_CARTEIRINHA_BENEFICIARIO = B.COD_CARTEIRINHA_BENEFICIARIO
	AND A.COD_SERVICO = B.COD_SERVICO)
  , 

  NUM_VPP2 as(
  SELECT 
  COD_SERVICO,
  NUM_VPP 
  FROM TB_405
  WHERE COD_SERVICO IN (SELECT 
  							COD_SERVICO 
  									FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_COD_SERVICOS`) )
SELECT 

* FROM TB_405
WHERE NUM_VPP IN (SELECT NUM_VPP FROM NUM_VPP2)
