create or replace table `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_WRK02_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOS` as
WITH T0 AS(SELECT DISTINCT
A.COD_BENEFICIARIO_CHAVE,
B.COD_CARTEIRINHA_ORIGINAL


 FROM `self-service-saude.VW_CONS_SAU.TB_EXP_CLASSES_SINISTRO_TOP` A
 INNER JOIN `self-service-saude.VW_CONS_SAU.DM_MGR_VIDA` B
 ON  A.COD_BENEFICIARIO_CHAVE = B.COD_BENEFICIARIO_CHAVE
 WHERE B.DAT_INICIAL = '2019-01-01'),


T1 AS (SELECT DISTINCT
-- COD_ANALITICO_BENEFICIARIO,
A.COD_CARTEIRINHA_BENEFICIARIO,
A.DE_PARA,
A.COD_SERVICO
FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_WRK01_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOS` A
INNER JOIN T0 B
ON A.COD_CARTEIRINHA_BENEFICIARIO = B.COD_CARTEIRINHA_ORIGINAL
WHERE DE_PARA IS NOT NULL),


TB_405 AS (SELECT 
  A.*,
  B.DE_PARA
  FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_WRK00_SDCC405_SINISTRO_SERVICOS_ONCOLOGICOS` A
  LEFT JOIN T1 B
  ON  A.COD_CARTEIRINHA_BENEFICIARIO = B.COD_CARTEIRINHA_BENEFICIARIO
  AND A.COD_SERVICO = B.COD_SERVICO)
--   select count(*) from tb_405, 
,
  NUM_VPP2 as(
  SELECT 
  COD_SERVICO,
  NUM_VPP 
  FROM TB_405
  WHERE COD_SERVICO IN (SELECT 
                COD_SERVICO 
                    FROM `sas-saude-alto-custo-hml.SBX_ALTO_CUSTO.TB_COD_SERVICOS`) and DE_PARA is not null)
SELECT 

* FROM TB_405
WHERE NUM_INTERNACAO IN (SELECT NUM_VPP FROM NUM_VPP2)
