CREATE OR REPLACE TABLE `self-service-saude.VW_COPARTICIPACAO.DS_COPART_VIDAS` AS 
 SELECT 
    V.ANO_MES
  , V.DAT_INICIAL
  , V.DAT_FINAL 
--  , V.COD_PLANO
   , V.COD_PRODUTO
   , V.COD_TIPO_PRODUTO
   , CASE WHEN V.COD_PRODUTO IN (567,563) THEN 'PME+' ELSE V.CARTEIRA END AS CARTEIRA
   , V.FLG_COPART_REVERS
   , V.NME_CATEGORIA
   , CA.IDC_TIPO_PLANO 
   , CASE
      WHEN IFNULL(COD_PADRAO, '') = 'A' THEN ' ENFERMARIA'
      WHEN IFNULL(COD_PADRAO, '') IN ('B','C') THEN ' APARTAMENTO'
      ELSE ''
    END ACOMODACAO
 --  , V.COD_PLANO_ANS
  , case when PM.COPART is null then 'N' ELSE PM.COPART END AS COPART
  , RP.COPART_PRODUTOS
 --  , V.COD_PREF_EMPRESA
 --  , V.COD_EMPRESA
 --  , V.NUM_APOL_SALIC
 --  , V.COD_GRUPO_ECON
 --  , V.NUM_GRUPO_APOLICE
 --  , REPLACE(V.DSC_RAZAO_SOCIAL,',','') DSC_RAZAO_SOCIAL
   ,SUM(V.VIDAS_ATIVAS) VIDAS_ATIVAS
   ,COUNT(DISTINCT CONCAT(V.COD_PREF_EMPRESA, V.COD_EMPRESA))  AS QTD_EMPRESAS
   ,COUNT( DISTINCT V.NUM_APOL_SALIC) AS QTD_APOLICES
   ,COUNT(DISTINCT V.COD_GRUPO_ECON) AS QTD_GRUPO_ECON
   ,COUNT(DISTINCT V.NUM_GRUPO_APOLICE) AS QTD_GRUPO_APOLICE
FROM (
 SELECT 
     AM.ANO_MES
   , AM.DAT_INICIAL 
   , AM.DAT_FINAL
   ,  PA.COD_PLANO
   , PA.COD_PRODUTO
    , PA.COD_PLANO_ANS
    , PS.COD_TIPO_PRODUTO
    , CE.NME_CATEGORIA
    , CE.COD_PADRAO
    , E.FLG_COPART_REVERS
    , E.COD_PREF_EMPRESA
    , E.COD_EMPRESA
    , E.NUM_APOL_SALIC
    , E.COD_GRUPO_ECON
    , E.NUM_GRUPO_APOLICE
    , E.DSC_RAZAO_SOCIAL
   , case WHEN PS.COD_TIPO_PRODUTO = 'A' THEN 'ADMINISTRADO'
        WHEN PS.COD_TIPO_PRODUTO = 'P' THEN 'PME'
        WHEN PS.COD_TIPO_PRODUTO = 'G' AND (E.FLG_CONTR_ADESAO = 'N' OR E.FLG_CONTR_ADESAO IS NULL) THEN 'EMPRESARIAL'
        WHEN PS.COD_TIPO_PRODUTO = 'G' AND E.FLG_CONTR_ADESAO = 'S' THEN 'ADESAO'
        WHEN PS.COD_TIPO_PRODUTO = 'I' THEN 'INDIVIDUAL'
        ELSE 'NÃO IDENTIFICADO' END AS CARTEIRA
    

 ,SUM(CASE WHEN B.DAT_EXCLUSAO >= B.DAT_ABERTURA_MATR 
     AND B.DAT_EXCLUSAO >= AM.DAT_FINAL 
     AND B.DAT_ABERTURA_MATR <= AM.DAT_FINAL
     THEN 1 ELSE 0 END ) AS VIDAS_ATIVAS

 FROM 
  (SELECT 
  COD_PREF_EMPRESA
    ,COD_BENEFICIARIO
    ,DAT_EXCLUSAO
    ,DAT_ABERTURA_MATR
    ,DENSE_RANK() OVER (PARTITION BY COD_PREF_EMPRESA, COD_BENEFICIARIO ORDER BY TMP_COMMIT_ORIGEM_CDC DESC) RANK_BENF 
   FROM OW_LAND_SAU_PRD.BENEFICIARIOS
  WHERE COD_BENEFICIARIO<>'' AND COD_SITUACAO_BENE<10) B
 LEFT OUTER JOIN
 (SELECT 
    COD_PREF_EMPRESA
     , COD_BENEFICIARIO
   , COD_EMPRESA
   , COD_PLANO
   , COD_CATEGORIA
   , COD_PROD
   , COD_CIA_RESP
     ,DENSE_RANK() OVER (PARTITION BY COD_PREF_EMPRESA, COD_EMPRESA, COD_BENEFICIARIO ORDER BY TMP_COMMIT_ORIGEM_CDC DESC) RANK_TIT
     FROM OW_LAND_SAU_PRD.TITULARES) T 
   ON  SUBSTR(B.COD_BENEFICIARIO, 1,13) = SUBSTR(T.COD_BENEFICIARIO, 1,13)
   AND B.COD_PREF_EMPRESA = T.COD_PREF_EMPRESA
   and T.RANK_TIT = 1 
 LEFT OUTER JOIN 
  (SELECT 
       COD_PREF_EMPRESA
     , COD_EMPRESA
     , COD_CATEGORIA
     , NME_CATEGORIA
     , COD_PADRAO
     , DENSE_RANK() OVER (PARTITION BY COD_PREF_EMPRESA, COD_EMPRESA, COD_CATEGORIA  ORDER BY TMP_COMMIT_ORIGEM_CDC DESC) RANK_CATEM
  FROM OW_LAND_SAU_PRD.CATEGORIA_EMPRESA)CE
     ON T.COD_EMPRESA = CE.COD_EMPRESA
    AND T.COD_PREF_EMPRESA = CE.COD_PREF_EMPRESA
    AND T.COD_CATEGORIA = CE.COD_CATEGORIA
    and CE.RANK_CATEM = 1
   LEFT OUTER JOIN
  (SELECT 
       COD_PROD
       , COD_TIPO_PRODUTO
     , DSC_PRODUTO
     , DENSE_RANK() OVER (PARTITION BY COD_PROD ORDER BY TMP_COMMIT_ORIGEM_CDC DESC) RANK_PROD
  FROM OW_LAND_SAU_PRD.PRODUTO_SAUDE) AS PS
  ON T.COD_PROD = PS.COD_PROD 
  AND PS.RANK_PROD = 1
 LEFT OUTER JOIN 
 (SELECT 
      COD_EMPRESA
    , COD_PREF_EMPRESA
    , DSC_RAZAO_SOCIAL
    , FLG_CONTR_ADESAO
    , COD_CIA
    , FLG_COPART_REVERS
    , COD_GRUPO_ECON
    , NUM_APOL_SALIC
    , SUBSTR(CAST(NUM_APOL_SALIC AS STRING),1,5) NUM_GRUPO_APOLICE    
   , DENSE_RANK() OVER (PARTITION BY COD_PREF_EMPRESA, COD_EMPRESA ORDER BY TMP_COMMIT_ORIGEM_CDC DESC) RANK_EMP
 FROM OW_LAND_SAU_PRD.EMPRESAS) E
   ON T.COD_EMPRESA = E.COD_EMPRESA
   AND T.COD_PREF_EMPRESA = E.COD_PREF_EMPRESA
   AND E.RANK_EMP = 1   
 LEFT OUTER JOIN 
 (SELECT 
     COD_PLANO
   , COD_PRODUTO
    , COD_PLANO_ANS
    , COD_CIA
    , DENSE_RANK() OVER (PARTITION BY COD_PLANO, COD_PRODUTO, COD_CIA ORDER BY TMP_COMMIT_ORIGEM_CDC DESC) RANK_PLANS
 FROM OW_LAND_SAU_PRD.PLANO_ANS) PA
 ON T.COD_PLANO = PA.COD_PLANO
 AND T.COD_PROD = PA.COD_PRODUTO
 AND E.COD_CIA = PA.COD_CIA
 and PA.RANK_PLANS = 1 
CROSS JOIN VW_CONS_SAU.VW_ANO_MES AM 
  where B.RANK_BENF = 1
 AND AM.ANO_MES >= 201801
-- AND AM.ANO_MES <= 202001
 GROUP BY 1, 2, 3,4, 5,6,7,8,9,10,11,12,13,14,15,16,17) V

LEFT OUTER JOIN  
   (SELECT PM.COD_ESPECIFICACAO,
        MAX(CASE WHEN PM.COD_ROT_PESQ_UNID IN (100,101,105,106) and VAL_PARTIC_FUNC > 0  THEN 'S' 
             WHEN PM.COD_ROT_PESQ_UNID = 0 AND AC.COD_ROT_CALC_ACUMU = '801' AND AC.COD_UNIDADE_LIMIT = '106' THEN 'S'
             ELSE 'N' END) AS COPART    
 FROM OW_LAND_SAU_PRD.PLANO_MEDICO PM
 LEFT JOIN OW_LAND_SAU_PRD.PLANO_ACUM_ESPEC AC
   ON cAST(AC.COD_PLANO AS STRING) = CAST(PM.COD_ESPECIFICACAO  AS STRING)
  AND CAST(AC.COD_GRP_ESTAT_INIC AS STRING) = CAST(PM.COD_GRP_ESTAT_INIC AS STRING)
  AND CAST(AC.COD_GRP_ESTAT_FIM  AS STRING) = CAST(PM.COD_GRP_ESTAT_FIM  AS STRING)
 WHERE PM.DAT_FIM_VIG_ESP >= current_DATE
   and PM.COD_GRP_ESTAT_INIC NOT IN (4164,4165) 
   and PM.COD_GRP_ESTAT_FIM NOT IN (4164,4165) 
 GROUP BY 1 ) PM
ON PM.COD_ESPECIFICACAO = V.COD_PLANO
LEFT JOIN 
(SELECT DISTINCT COD_PRODUTO, COD_PLANO_ANS, FLG_COPARTICIPACAO AS COPART_PRODUTOS
FROM `VW_CONS_SAU.RELAC_PRODUTO_ANS`) RP
ON CAST(RP.COD_PRODUTO AS STRING) = CAST(V.COD_PRODUTO AS STRING)
AND CAST(RP.COD_PLANO_ANS AS STRING) = CAST(V.COD_PLANO_ANS AS STRING)
LEFT OUTER JOIN OW_LAND_SAU_PRD.CATEGORIA_ATU CA
  ON TRIM(V.NME_CATEGORIA) = TRIM(CA.NME_CATEGORIA)   
  where VIDAS_ATIVAS > 0

GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12
####teste
